### ISSUE TITLE
Implementation differences between your code and Kaiming's paper

### ISSUE THREAD

**Issue by shepnerd** [AmirooR/FlannImageCompletion#1]
Hi, Amir. When using your code, the boundary effects are obvious (with the default parameters in main.cpp, shown in [1](https://user-images.githubusercontent.com/5066504/37892643-0a7a5cc6-310b-11e8-8d28-ed5551c5f0f8.png)). Besides, the functions smoothFn and dataFn seem not to work. Do I miss something?
Could you share about the differences between your implementation and Kaiming's paper?

**Comment by AmirooR** [comment]
Hi @shepnerd , sorry for the late reply. This code is written many years ago as simple reimplementation of the paper. What I remember is that there must be some differences with the original paper as I use flann for finding the nearest neighbours. Also this [issue](https://github.com/AmirooR/FlannImageCompletion/issues/2) might be helpful.

**Comment by shepnerd** [comment]
Thank you for your clarification.

--
Best,
Yi

Amir <notifications@github.com> 于2019年1月10日周四 上午11:47写道：
